### ISSUE TITLE
Support full display of long lines

### ISSUE THREAD

**Issue by chris-aeviator** [PaulJuliusMartinez/jless#116] opened 2023-03-20 11:29 UTC
Nowadays machine learning (training) datasets often come as JSONL documents. When working with natural language, a typical user utterance or dialog context often comes with all information in one sentence, which leads to long lines.

It would be benefitial if jless could collapse/expand long lines instead of truncating them

Example
![grafik](https://user-images.githubusercontent.com/11522213/226326790-c98c5a41-70d8-4190-be13-6b075957b4c3.png)

**Comment by nezda** [comment] 2023-04-22 11:25
Duplicate of https://github.com/PaulJuliusMartinez/jless/issues/34

**Comment by PaulJuliusMartinez** [comment] 2023-07-17 03:10
I haven't implemented line wrapping yet, but the `ps` command in the [latest version](https://github.com/PaulJuliusMartinez/jless/releases/tag/v0.9.0) should be able to help you here. It will print out the full string (with any special characters unescaped) out to the screen. (If you don't want characters to be escaped, you can use `pp`.)

**Comment by indigoviolet** [comment] 2023-09-28 21:10
@PaulJuliusMartinez this is great; it would be awesome if `ps` could go into the current `PAGER` or a configurable command. Then I could jump to `less`, or even `jless` for nested JSON.

Thank you for this tool!

**Comment by PaulJuliusMartinez** [comment] 2024-06-01 18:59
Closing as a duplicate of https://github.com/PaulJuliusMartinez/jless/issues/34.

**Closed by PaulJuliusMartinez** 2024-06-01 18:59 UTC
